### PR TITLE
✨ Add structured meta data

### PR DESCRIPTION
**Pull request by robinvanopstal**
Add `METADATA.yaml` to working group repository in order to provide the following data for #1699 in a structured way:
- Group Name 
- Short Description
- Facilitator
- Members
- Communication Channels

/cc @pbakaus

### CODE REVIEW

**Comment by robinvanopstal** [comment]
@googlebot I fixed it.

**Comment by robinvanopstal** [comment]
What is the status here @pbakaus ? :)

**Comment by pbakaus** [comment]
not sure! Paging @sebastianbenz

**Comment by pbakaus** [comment]
but more generally: What do you need from me? a LGTM?

**Comment by sebastianbenz** [comment]
@pbakaus merging the PR would be splendid.

**Comment by pbakaus** [comment]
sadly I cannot, because I don't have write access. @dvoytenko?

**Review by dvoytenko — APPROVED** [review]

**Comment by dvoytenko** [comment]
Merged! Thanks!

**Pull request merged**
